extend type Mutation {
  """
  ✨ Insert a single `AfluenciaStat` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  afluenciaStat_insert(
    """
    Data object to insert into the table.
    """
    data: AfluenciaStat_Data!
  ): AfluenciaStat_KeyOutput! @fdc_generated(from: "AfluenciaStat", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Category` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  category_insert(
    """
    Data object to insert into the table.
    """
    data: Category_Data!
  ): Category_KeyOutput! @fdc_generated(from: "Category", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Establishment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  establishment_insert(
    """
    Data object to insert into the table.
    """
    data: Establishment_Data!
  ): Establishment_KeyOutput! @fdc_generated(from: "Establishment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Turn` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  turn_insert(
    """
    Data object to insert into the table.
    """
    data: Turn_Data!
  ): Turn_KeyOutput! @fdc_generated(from: "Turn", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WaitTime` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  waitTime_insert(
    """
    Data object to insert into the table.
    """
    data: WaitTime_Data!
  ): WaitTime_KeyOutput! @fdc_generated(from: "WaitTime", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AfluenciaStat` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  afluenciaStat_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AfluenciaStat_Data!]!
  ): [AfluenciaStat_KeyOutput!]! @fdc_generated(from: "AfluenciaStat", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Category` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  category_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Category_Data!]!
  ): [Category_KeyOutput!]! @fdc_generated(from: "Category", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Establishment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  establishment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Establishment_Data!]!
  ): [Establishment_KeyOutput!]! @fdc_generated(from: "Establishment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Turn` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  turn_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Turn_Data!]!
  ): [Turn_KeyOutput!]! @fdc_generated(from: "Turn", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WaitTime` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  waitTime_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WaitTime_Data!]!
  ): [WaitTime_KeyOutput!]! @fdc_generated(from: "WaitTime", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AfluenciaStat` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AfluenciaStat`.
  """
  afluenciaStat_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AfluenciaStat_Data!
  ): AfluenciaStat_KeyOutput! @fdc_generated(from: "AfluenciaStat", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Category` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Category`.
  """
  category_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Category_Data!
  ): Category_KeyOutput! @fdc_generated(from: "Category", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Establishment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Establishment`.
  """
  establishment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Establishment_Data!
  ): Establishment_KeyOutput! @fdc_generated(from: "Establishment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Turn` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Turn`.
  """
  turn_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Turn_Data!
  ): Turn_KeyOutput! @fdc_generated(from: "Turn", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WaitTime` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WaitTime`.
  """
  waitTime_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WaitTime_Data!
  ): WaitTime_KeyOutput! @fdc_generated(from: "WaitTime", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AfluenciaStat` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AfluenciaStat`.
  """
  afluenciaStat_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AfluenciaStat_Data!]!
  ): [AfluenciaStat_KeyOutput!]! @fdc_generated(from: "AfluenciaStat", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Category` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Category`.
  """
  category_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Category_Data!]!
  ): [Category_KeyOutput!]! @fdc_generated(from: "Category", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Establishment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Establishment`.
  """
  establishment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Establishment_Data!]!
  ): [Establishment_KeyOutput!]! @fdc_generated(from: "Establishment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Turn` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Turn`.
  """
  turn_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Turn_Data!]!
  ): [Turn_KeyOutput!]! @fdc_generated(from: "Turn", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WaitTime` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WaitTime`.
  """
  waitTime_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WaitTime_Data!]!
  ): [WaitTime_KeyOutput!]! @fdc_generated(from: "WaitTime", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AfluenciaStat` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AfluenciaStat` or `null` if not found.
  """
  afluenciaStat_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AfluenciaStat_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AfluenciaStat_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AfluenciaStat_Data!
  ): AfluenciaStat_KeyOutput @fdc_generated(from: "AfluenciaStat", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Category` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Category` or `null` if not found.
  """
  category_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Category_Data!
  ): Category_KeyOutput @fdc_generated(from: "Category", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Establishment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Establishment` or `null` if not found.
  """
  establishment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Establishment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Establishment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Establishment_Data!
  ): Establishment_KeyOutput @fdc_generated(from: "Establishment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Turn` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Turn` or `null` if not found.
  """
  turn_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Turn_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Turn_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Turn_Data!
  ): Turn_KeyOutput @fdc_generated(from: "Turn", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WaitTime` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WaitTime` or `null` if not found.
  """
  waitTime_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WaitTime_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WaitTime_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WaitTime_Data!
  ): WaitTime_KeyOutput @fdc_generated(from: "WaitTime", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AfluenciaStat` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  afluenciaStat_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AfluenciaStat_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AfluenciaStat_Data!
  ): Int! @fdc_generated(from: "AfluenciaStat", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Category` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  category_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Category_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Category_Data!
  ): Int! @fdc_generated(from: "Category", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Establishment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  establishment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Establishment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Establishment_Data!
  ): Int! @fdc_generated(from: "Establishment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Turn` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  turn_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Turn_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Turn_Data!
  ): Int! @fdc_generated(from: "Turn", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WaitTime` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  waitTime_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WaitTime_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WaitTime_Data!
  ): Int! @fdc_generated(from: "WaitTime", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AfluenciaStat` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  afluenciaStat_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AfluenciaStat_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AfluenciaStat_FirstRow
  ): AfluenciaStat_KeyOutput @fdc_generated(from: "AfluenciaStat", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Category` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  category_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow
  ): Category_KeyOutput @fdc_generated(from: "Category", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Establishment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  establishment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Establishment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Establishment_FirstRow
  ): Establishment_KeyOutput @fdc_generated(from: "Establishment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Turn` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  turn_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Turn_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Turn_FirstRow
  ): Turn_KeyOutput @fdc_generated(from: "Turn", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WaitTime` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  waitTime_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WaitTime_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WaitTime_FirstRow
  ): WaitTime_KeyOutput @fdc_generated(from: "WaitTime", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AfluenciaStat` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  afluenciaStat_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AfluenciaStat_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AfluenciaStat", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Category` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  category_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Category_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Category", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Establishment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  establishment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Establishment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Establishment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Turn` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  turn_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Turn_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Turn", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WaitTime` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  waitTime_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WaitTime_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WaitTime", purpose: DELETE_MULTIPLE)
}
