extend type Query {
  """
  ✨ Look up a single `AfluenciaStat` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  afluenciaStat(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AfluenciaStat_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AfluenciaStat_FirstRow
  ): AfluenciaStat @fdc_generated(from: "AfluenciaStat", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Category` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  category(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow
  ): Category @fdc_generated(from: "Category", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Establishment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  establishment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Establishment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Establishment_FirstRow
  ): Establishment @fdc_generated(from: "Establishment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Turn` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  turn(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Turn_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Turn_FirstRow
  ): Turn @fdc_generated(from: "Turn", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WaitTime` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  waitTime(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WaitTime_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WaitTime_FirstRow
  ): WaitTime @fdc_generated(from: "WaitTime", purpose: QUERY_SINGLE)
  """
  ✨ List `AfluenciaStat` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  afluenciaStats(
    """
    Filter condition to narrow down the query results.
    """
    where: AfluenciaStat_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AfluenciaStat_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AfluenciaStat_Having
  ): [AfluenciaStat!]! @fdc_generated(from: "AfluenciaStat", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Category` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  categories(
    """
    Filter condition to narrow down the query results.
    """
    where: Category_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Category_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Category_Having
  ): [Category!]! @fdc_generated(from: "Category", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Establishment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  establishments(
    """
    Filter condition to narrow down the query results.
    """
    where: Establishment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Establishment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Establishment_Having
  ): [Establishment!]! @fdc_generated(from: "Establishment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Turn` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  turns(
    """
    Filter condition to narrow down the query results.
    """
    where: Turn_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Turn_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Turn_Having
  ): [Turn!]! @fdc_generated(from: "Turn", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WaitTime` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  waitTimes(
    """
    Filter condition to narrow down the query results.
    """
    where: WaitTime_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WaitTime_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WaitTime_Having
  ): [WaitTime!]! @fdc_generated(from: "WaitTime", purpose: QUERY_MULTIPLE)
}
