type User @table {
  uid: String!
  email: String!
  nombre: String!
  apellido: String!
  rol: String!
  createdAt: Timestamp!
  telefono: String
  deletedAt: Timestamp
}

type Category @table {
  nombre: String!
  icono: String!
  activa: Boolean!
}

type Establishment @table {
  nombre: String!
  nombreNormalizado: String!
  direccion: String!
  descripcion: String
  category: Category!
  admin: User!
  activo: Boolean!
  abierto: Boolean!
  createdAt: Timestamp!
}

type Turn @table {
  user: User!
  establishment: Establishment!
  codigo: String!
  tipo: String!
  estado: String!
  posicion: Int!
  solicitadoEn: Timestamp!
  atendidoEn: Timestamp
  canceladoEn: Timestamp
}

type WaitTime @table {
  establishment: Establishment!
  minutos: Int!
  actualizadoEn: Timestamp!
}

type AfluenciaStat @table {
  establishment: Establishment!
  category: Category!
  totalTurnos: Int!
  turnosPrioritarios: Int!
  fechaHora: Timestamp!
  periodo: String!
}